### ISSUE TITLE
Not creating Resource Nodes on server

### ISSUE THREAD

**Issue by camosak** [spacebuild/spacebuild#64]
On my server when I use the resource node stool, no nod is generated. I do not get any lua errors. It is a linux server.

**Comment by N3X15** [comment]
I went through and systematically changed every damn filename to the proper case with a script, and still run into this problem.

Please let us know what you did, @camosak.

**Comment by N3X15** [comment]
Okay, here's an update.  

I went ahead and forked the project and made a huge number of fixes, including fixing file capitalization and disabling usage of utils.IsModelValid/utils.IsPropValid (they were both returning false positives on Linux).  I also went through and drastically reduced the amount of console spam.  There's still some work to be done, but Resource Nodes are now working on my server.

Diff: https://github.com/SnakeSVx/spacebuild/compare/master...N3X15:master
Fork: https://github.com/N3X15/spacebuild

I don't know for how long I'll be able to continue cleaning up SB3, since I'll be moving to Kent, WA soon, but I hope to have most of the major bugs fixed.

**Comment by generalwrex** [comment]
I might be able to get this accepted into the repo, so we have some activity, heh :)

**Comment by awilliamson** [comment]
We fixed the linux folder naming issues with SB4. Just do a cherry-pick for the specific commit from there.

But seeing as how SB3 isn't actually supported anymore, these kinds of fixes are trivial for most established servers.

**Comment by N3X15** [comment]
That's great and all, but for people just starting a server, not many guides are out there on how to set up SB4, and from what I have seen in the repo, SB4 isn't even updated anymore (unless it moved to another namespace).  

Searching for this particular problem only brings up this issue, so it makes sense to link to the changes that need to be made, since it's not an obvious fix.

**Comment by generalwrex** [comment]
For sakes of this issue, I was having the same problem until I merged in the workshop branch into master, which contained the casing fixes.  And now the nodes spawn again :)
