### ISSUE TITLE
Spacebuild: Workshop Edition  ( General Workshop Thread )

### ISSUE THREAD

**Issue by generalwrex** [spacebuild/spacebuild#84]
Currently I was thinking about making a special workshop edition of spacebuild 3, what do you guys think?

Once we get both SBEP and SB3 ironed out we can get them on the shop!

I will be creating a program that will have authentication to allow you guys to push changes to the workshop without me having to actually do it manually, or maybe just have it watch a text file in the repository when we want it to update the workshop, and have a git hook take care of everything

If anyone has any c# skills let me know, maybe we can make a good program for the community that bypasses the damn "Only author can update the workshop" bull for everyone!

There are many possibilities, lets wrap our heads around it!

**Comment by generalwrex** [comment]
It seems we have some file renaming  ( and backwards compatibility scripts to do for sb addons ) before we can get it on the workshop.  I tried to create a GMA from the new (local) workshop branch and got a major file verification for multiple capital letters ;)

**Comment by X-Coder** [comment]
File renaming is needed anyway for proper linux support.
If you give me a little time, I can submit my changes, because I already lower cased most of the stuff for my linux server and changed the lua code.

Only the file which feeds the dupefixer script needs to be checked for missing file renames (If I remember right lower case file name changes doesn't matter here because I fixed it somewhere in LUA, so only if the filename itself changes it needs to be added to the list).

I just have to sort my stuff because it a mess right now.


Your workshop automatic is a good idea. Maybe we could add a workshop branch to the repository and if something is pushed into this, it could be automatically pushed to workshop using a hook. So this has to be a stable, tested branch.

Developing could be happening on master branch and if no errors found merged or cherry picked into workshop branch. This branch should be stable too.

**Comment by generalwrex** [comment]
I got all the (models/materials/sounds) folders/files renamed where gmad created the gma. If you just wanted to work on the Lua part.

**Comment by generalwrex** [comment]
Workshop branch pushed with the file renames:

https://github.com/SnakeSVx/spacebuild/tree/workshop

**Comment by generalwrex** [comment]
We need someone that runs a GMod client natively on linux to help us test out our https://github.com/SnakeSVx/spacebuild/tree/workshop branch to make sure it works! If anyone can help, please leave a comment or add me on steam at http://steamcommunity.com/id/webwrex/ Also please message me on here if you do add me, so I know who you are, or I wont accept the request ;)

**Comment by philxyz** [comment]
I run gmod natively under Linux. I don't have a lot of time to chat on steam though these days. I used to work on DarkRP (v2.2) before Falco took it over. I could probably try it out...

**Comment by generalwrex** [comment]
It should work on linux just fine now, that was before some changes that we did ;)

**Comment by philxyz** [comment]
I'll have a quick check anyway - it took a few hours to sort out a disk space issue first.

**Comment by philxyz** [comment]
It seems to work fine - I can't see any Lua errors. Only issue is, there is gravity in space.

**Comment by generalwrex** [comment]
Lets use the forums now https://spacebuildmod.com/forum
